eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    lk.ijse.eca: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG