spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    host: localhost
    port: 13500
    database: eca
    username: root
    password: mongodb
    authentication-database: admin

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
